### ISSUE TITLE
`serde` support + Copy

### ISSUE THREAD

**Issue by korrat** [gnp/isin-rs#1]
Thank you for this useful crate!

I'm currently using it in a project of mine inside a parser, which would benefit a lot from support for the [`serde`](https://serde.rs/) crate. Would you accept a PR in this vein?

As far as I can tell, `ISIN` could also be `Copy`. If you don't mind, I would include said change as well.

**Comment by gnp** [comment]
Thank you!

Yes, I'd be interested in a PR that added serde support as a feature + optional dependency.

I'm interested also in Copy though I'd prefer separate PR.
