### ISSUE TITLE
Consider byte array serialization for binary formats

### ISSUE THREAD

**Issue by korrat** [gnp/isin-rs#4]
In #3, basic support for serde has been added. For now, this always serializes an `ISIN` as a `str`, but for binary formats, where human readability is not necessary, we could serialize the inner `[u8; 12]` array directly, which might be more efficient (see the [serde docs](https://serde.rs/impl-serialize.html#serializing-a-tuple)).

From a user's perspective, this could be totally transparent by using [serde::Serializer::is_human_readable](https://docs.rs/serde/latest/serde/trait.Serializer.html#method.is_human_readable) to detect when we're serializing to non-human-readable formats and switching to byte array serialization then.

**Comment by gnp** [comment]
I'm not familiar with serde's binary format support. Is there one you are familiar enough with that we could have both a JSON example and a Format XXX example?

**Comment by korrat** [comment]
Of course, I can provide an example of using the new serde support with Postcard. I will let you know, once I have that.

**Comment by korrat** [comment]
I've pushed an example using `postcard` at my fork: https://github.com/korrat/isin-rs/blob/3a30ae793fffd3785560bc487948326c801c9308/examples/serde_postcard.rs

**Comment by gnp** [comment]
Looks good. I'd be happy to incorporate. From your ealier post it seemed like the idea was to have the serde integration detect binary vs text format and auto select binary for binary format.

Would there be a way for someone who was using binary format but really wanted to treat as a string, to do so?

Since the identifier is ASCII the bytes are the same but the envelope of a fixed length array vs a string could differ and that might be important to the user.

**Comment by korrat** [comment]
Yes, it is possible to add a way for users of the functionality to override the serialization format. In fact, there are multiple options: 

1. Users could use serde's [`with` attribute](https://serde.rs/field-attrs.html#with) to force string serialization. We could provide a corresponding module that encodes the behaviour, or users could write the function themselves, it's a single line function.
2. We could do something similar to the [`time` crate](https://docs.rs/time/latest/time/#feature-flags), where there are two feature flags for turning on serde support, one for binary serialization and one adding support for human-readable formats on top. If the latter flag is enabled and human-readable serialization is supported, values are serialized as strings (e.g., [`impl Serialize for time::Date`](https://docs.rs/time/0.3.30/src/time/serde/mod.rs.html#223-235)).

   For this crate, we could support two flags, one enabling binary serialization and one enabling human-readable serialization. If both flags are enabled, the implementation of serialize would select the appropriate format based on [`serde::Serializer::is_human_readable`](https://docs.rs/serde/latest/serde/trait.Serializer.html#method.is_human_readable).

We could also decide to forego byte array serialization completely, since the size overhead is pretty minimal (1 usize) and may not justify additional maintenance overhead for a second implementation. Users that need truly minimal serialization could still implement the first option themselves. We could also add an example, showcasing the manual implementation.

**Comment by gnp** [comment]
Based on this:

> We could also decide to forego byte array serialization completely, since the size overhead is pretty minimal (1 usize) and may not justify additional maintenance overhead for a second implementation. Users that need truly minimal serialization could still implement the first option themselves.

I'm going to close this PR. Thanks for the suggestion!
